//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduatesProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        public Persons()
        {
            this.PersonsProffesions = new HashSet<PersonsProffesions>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Biography { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> GraduateYear { get; set; }
        public Nullable<double> GPAofCertificate { get; set; }
        public string DiplomaPaperTopic { get; set; }
        public string SupervisorOfDiplomaPaper { get; set; }
        public string Email { get; set; }
        public string Skype { get; set; }
        public string PhoneNumber { get; set; }
        public string ActivityInStudent { get; set; }
        public Nullable<int> PhotoId { get; set; }
        public Nullable<bool> HasWorkNow { get; set; }
        public Nullable<bool> IsMarried { get; set; }
        public string ReviewsAboutInstitute { get; set; }
        public Nullable<bool> FundedByNBU { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Photos Photos { get; set; }
        public virtual ICollection<PersonsProffesions> PersonsProffesions { get; set; }
    }
}
