//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduatesProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonsProffesions
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int StructureId { get; set; }
        public int PositionId { get; set; }
        public int Year { get; set; }
        public string Adress { get; set; }
        public string Description { get; set; }
    
        public virtual Persons Persons { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Structures Structures { get; set; }
    }
}
