//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduatesProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public Photos()
        {
            this.Persons = new HashSet<Persons>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Guid { get; set; }
        public string VirtualUrl { get; set; }
        public int PersonId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsOnServer { get; set; }
    
        public virtual ICollection<Persons> Persons { get; set; }
    }
}
