//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduatesProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.SystemUsers = new HashSet<SystemUsers>();
        }
    
        public int Id { get; set; }
        public string RoleSystemName { get; set; }
        public string RoleLabel { get; set; }
    
        public virtual ICollection<SystemUsers> SystemUsers { get; set; }
    }
}
